name: CI

on:
  push:
    tags:
      - '*'  # Triggers on any tag push
    branches:
      - '**' # Triggers on any branch push

# sources:
# workflow: https://github.com/Roblox/setup-foreman
# ci: https://github.com/Roblox/roact/blob/master/.github/workflows/ci.yml#L12

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ewd3v/setup-luau@v0.1.0

      - name: Download global Roblox types
        shell: bash
        run: curl -O https://raw.githubusercontent.com/JohnnyMorganz/luau-analyze-rojo/master/globalTypes.d.lua

      - name: Analyze
        shell: bash
        run: luau-analyze --project=default.project.json --defs=globalTypes.d.lua --defs=testez.d.lua src/

